name: Deployment
on:
  check_run:
    types: [completed]
    
jobs:
  make_deployment:
    name: Make Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment
        uses: actions/github-script@v5
        id: deployment
        with:
          script: |
            const { DEPLOYMENT_ID } = process.env
            
            const { data: deployment } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.check_run.head_sha
            })
            
            const matches = /Preview URL[\s\S]*(https:\/\/.*\.pages\.dev)[\s\S]*logs\]\((.*)\)/gm.exec(context.payload.check_run.output.summary)
            const environment_url = matches[1]
            const logs_url = matches[2]
            
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.id,
              environment_url,
              log_url,
              state: 'success'
            })
