name: Deployment
on:
  check_run:
    types: [completed]
    
jobs:
  make_deployment:
    name: Make Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Deployment
        uses: actions/github-script@v5
        with:
          script: |
            const { DEPLOYMENT_ID } = process.env
            
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: DEPLOYMENT_ID
            })
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.id,
              state: 'in_progress'
            })
        env:
          DEPLOYMENT_ID: ${{ github.event.check_run.head_sha }}
      - name: Parse Preview Link
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.check_run.output.summary }}
          regex: 'Preview URL.*>(https:\/\/.*\.pages.dev).*logs]\((.*)\)'
      - name: Create Deployment
        uses: actions/github-script@v5
        with:
          script: |
            const { DEPLOYMENT_ID, ENVIRONMENT_URL, LOG_URL } = process.env
            
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: DEPLOYMENT_ID,
              environment_url: ENVIRONMENT_URL,
              log_url: LOG_URL,
              state: 'success'
            })
        env:
          deployment_id: ${{ github.event.check_run.head_sha }}
          environment_url: ${{ steps.regex-match.outputs.group1 }}
          log_url: ${{ steps.regex-match.outputs.group2 }}
